add /DELETE user/:id
Kirosana15/moodup-recipes-nest pull request #42
Opened 2022-08-31 14:01 UTC by Kirosana15

2022-09-02 12:53 UTC, arkus7 approved these changes

2022-09-02 12:53 UTC, arkus7 commented on src/user/test/delete.spec.ts
> +  });
This could be `beforeAll()`

2022-09-02 12:53 UTC, arkus7 commented on src/user/test/delete.spec.ts
> +    await closeConnections();
we should close the test module somewhere

2022-09-02 12:53 UTC, arkus7 commented on src/user/test/delete.spec.ts
> +  it('should return deleted recipe', async () => {
`recipe`? it should be `user`

2022-09-02 12:53 UTC, arkus7 commented on src/user/test/e2e/deleteUser.e2e.spec.ts
> +  });
`beforeAll`?

2022-09-02 12:53 UTC, arkus7 commented on src/user/user.controller.ts
> +  @UseGuards(OwnerGuard)
What does `Owner` mean in this context? Shouldn't only admin have option to call this request?

2022-09-02 12:59 UTC, arkus7 requested changes
I think we should create a test app for the whole suite once, in `beforeAll` not `beforeEach`

2022-09-05 08:44 UTC, Kirosana15 commented on src/user/user.controller.ts
> +  @UseGuards(OwnerGuard)
Owner of an account. I wanted to leave the option for users to delete their own accounts. Admin can delete any account.

2022-09-05 08:49 UTC, merged